version: 2.1

executors:
  docker:
    docker:
      - image: cimg/rust:1.70.0
  arm:
    machine:
      image: ubuntu-2004:current 
    resource_class: arm.medium
    environment:
      RUSTUP_VERSION: 1.70.0

jobs:
  test-docker:
    executor: docker
    steps:
      - checkout
      - run: cargo test

  test-arm:
    executor: arm
    steps:
      - checkout
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: cargo test

workflows:
  test:
    jobs:
      - test-docker
      - test-arm
